name: Gen
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Gen dump
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn ts-node script/gen-template-dump.ts
      - run: bash ./script/push-if-changed.bash
