name: Gen
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Gen dump
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn ts-node script/gen-template-dump.ts
      - run: git add templates/gen
      - run: |
        git diff --exit-code --quiet templates/src
        if [ 0 -ne $? ]; then
          git config --global user.email "CI@github"
          git config --global user.name "CI"
          git commit -m "[CI] Gen templates/gen"
          git push origin master
        fi
