name: Gen
on: [push, pull_request]
# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: echo 1
