name: Gen
on: [push, pull_request]
# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: echo 1 > .dump
      - run: git add .dump
      - run: git config --global user.email "miz404@gmail.com"
      - run: git config --global user.name "CI"
      - run: git commit -m "Gen .dump"
      - run: git remote set-url origin https://mizchi:${GITHUB_TOKEN}@github.com/mizchi/browserpack-v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git push origin master
